parser/config/routes.rb
Parser::Application.routes.draw do
  get "posts/new"
  match 'domain_rules/', to: 'domain_rules#create', via: 'post', as: "domain_rules_create"
  resources :domain_rules
  match '/scrapers/:id/edit', to: "scrapers#edit", via: 'post', as: "edit_scraper"
  resources :scrapers
  match '/scrapers/:id/update', to: "scrapers#update", via: 'get', as: "scraper_update"
  resources :posts 

end

parser/app/models/scraper.rb
class Scraper < ActiveRecord::Base
end

parser/app/controllers/scrapers_controller.rb
require '/users/bneuman/rails-parser/parser/app/models/formatter/strippers'

class ScrapersController < ApplicationController

	def create
		url = params[:scrapings][:url]
		noko = nokoify(url)
		@scraper = Scraper.create(url: url, html_head: noko[:head], html_body: noko[:body])
		redirect_to @scraper
	end

	def show
		@scraper = Scraper.find(params[:id])
		@scraper.save
	end

	def nokoify(url)
		doc = Nokogiri::HTML(open(url))
		head = doc.css('head')[0]
		body = doc.css('body')[0]
		noko_string = {head: head.serialize, body: body.serialize}
	end
	
	def edit
		@scraper = Scraper.find(params[:id])
		@scraper.good_rules = save_rules_helper(params[:good]) unless params[:good] == nil
		@scraper.bad_rules = save_rules_helper(params[:bad]) unless params[:bad] == nil
		@scraper.save
		render nothing: true
	end

	def update
		scraper = Scraper.find(params[:id])
		redirect_to edit_post_path(url: scraper.url) 
		#WANT TO REDIRECT TO posts CREATE ACTION
	end

	def save_rules_helper(rules)
		rules_formatted = rules.values.collect do |rule|
			{name: rule['name'].downcase,
				attributes: attr_helper(rule['attributes'].values),}
		end
		JSON.generate(rules_formatted).gsub("=>", ":")
	end
	
	def attr_helper(attributes)
		attributes.reject! {|attribute| attribute['name'] == 'style'}
		attributes.collect do |attribute|
			{name: attribute['name'],
			values: attribute['values'].split(' '),}
		end
	end

end

parser/app/helpers/scrapers_helper.rb
module ScrapersHelper
end

parser/app/views/scrapers/index.html.erb
<HTML>
<head>
<%= @html[:head].html_safe %>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>
<body>
<%= @html[:body].html_safe %>
<div id="fuckespn">
<button onclick="selectify()" id="floatbutton">Click when you have selected UNWANTED text</button>
<button id="floatbutton2" onclick="body_finder()">Click when you have selected WANTED text</button>
<button onclick="send_info()" id="floatbutton3">Send info</button>
<div id="popUpDialog">
<button id="yesbutton">Yes</button>
<button id="nobutton">No</button>
<button id="toomuch">Too much?</button>
<button id="toolittle">Too little?</button>
<button id="bcktrk">Backtrack?</button>
</div>
</div>
</body>
</html>

parser/app/views/scrapers/new.html.erb
<%= csrf_meta_tags %>
<%= form_for(:scrapings, url: scrapers_path) do |f| %>
	<%= f.label :url %>
	<%= f.text_field :url %>

	<%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
<% end%>

parser/app/views/scrapers/show.html.erb
d<HTML>
<head>
<%= @scraper.html_head.html_safe %>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>
<body>
<div id="cheatespn">
<button onclick="selectify()" id="floatbutton">Click when you have selected UNWANTED text</button>
<button id="floatbutton2" onclick="body_finder()">Click when you have selected WANTED text</button>
<button onclick="save_info()" id="floatbutton3">Send info</button>
<%= button_to 'Generalize rule', domain_rules_create_path(:id => @scraper.id) %>
<div id="popUpDialog">
<button id="yesbutton">Yes</button>
<button id="nobutton">No</button>
<button id="toomuch">Too much?</button>
<button id="toolittle">Too little?</button>
<button id="bcktrk">Backtrack?</button>
</div>
</div>
<%= @scraper.html_body.html_safe %>
<footer>
	<h4>
	<%= link_to 'Update',  scraper_update_path %>
</h4>
</footer>
</body>
</html>

parser/app/views/scrapers/update.html.erb
<HTML>
<head>
<%= @scraper.mod_html.html_safe %>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</body>
</html>