parser/config/routes.rb
Parser::Application.routes.draw do
  get "posts/new"
  match 'domain_rules/', to: 'domain_rules#create', via: 'post', as: "domain_rules_create"
  resources :domain_rules
  match '/scrapers/:id/edit', to: "scrapers#edit", via: 'post', as: "edit_scraper"
  resources :scrapers
  match '/scrapers/:id/update', to: "scrapers#update", via: 'get', as: "scraper_update"
  resources :posts 

end

parser/app/models/post.rb
class Post < ActiveRecord::Base
	validates :url, presence: true, uniqueness: {case_sensitive: false}
end

parser/app/controllers/posts_controller.rb
require '/users/bneuman/rails-parser/parser/app/models/formatter/strippers'

class PostsController < ApplicationController
  def new
  end

  def create
  	sql_configure(DomainRule.all)
  	url = params[:posts][:url]
  	@post = Post.find_or_create_by_url(url)
  	if @post.f_html == nil
  		doc = HTML_Doc.new(url)
  		@post.html = doc.doc.serialize
  		@post.f_html = doc.processed_doc
  		@post.save
  	end

  	redirect_to @post
  end

  def show
  	@post = Post.find(params[:id])
  	render
  end

  def edit
    sql_configure(DomainRule.all)
    url = params[:url]
    @post = Post.find_or_create_by_url(url)
    if @post.html == nil
      doc = HTML_Doc.new(url)
      @post.html = doc.doc.serialize
      @post.f_html = doc.processed_doc
    else
      doc = Nokogiri::HTML(@post.html)
      f_html = Stripper.new(@post.url, doc).processed_doc
      if f_html != @post.f_html
        @post.f_html = f_html
      end
    end
    @post.save
    redirect_to @post
  end
end

parser/app/helpers/posts_helper.rb
module PostsHelper
end

parser/app/views/posts/new.html.erb
<%= csrf_meta_tags %>
<%= form_for(:posts, url: posts_path) do |f| %>
	<%= f.label :url %>
	<%= f.text_field :url %>

	<%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end%>

parser/app/views/posts/show.html.erb
<HTML>
<head>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>
<body>
	<%= @post.f_html.html_safe %>

<footer>
	<h4>
	<%= link_to 'Reformulate Rules',  new_scraper_path(url: @post.url) %>
</h4>
</footer>
</body>
</html>

parser/app/views/posts/update.html.erb
<HTML>
<head>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
</head>
<body>
	<%= @post.f_html.html_safe %>

<footer>
	<h4>
	<%= link_to 'Reformulate Rules',  new_scraper_path(url: @post.url) %>
</h4>
</footer>
</body>
</html>